# By default, SwiftLint uses a set of sensible default rules you can adjust:
 disabled_rules: # rule identifiers turned on by default to exclude from running
   - trailing_whitespace
   - identifier_name
   - function_body_length
 opt_in_rules: # some rules are turned off by default, so you need to opt-in

 included: # paths to include during linting. `--path` is ignored if present.

 excluded: # paths to ignore during linting. Takes precedence over `included`.
   - Pods

 line_length: 250
